# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tracking_location' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for tracking_location
  pod 'GoogleMaps'

  target 'tracking_location-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tracking_locationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
