# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoTrackingLocation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'GoogleMaps'
  pod 'Socket.IO-Client-Swift', '~> 11.0.0'
  # Pods for DemoTrackingLocation

end
